// ============================================================
// AI-Generated Jenkinsfile
// Repo: Python-Project | Env: dev
// Stack: python / python / pip
// Generated by Backstage AI DevOps Scaffolder
// ============================================================

pipeline {
    agent any

    environment {
        APP_NAME = "Python-Project".toLowerCase().trim()
        DOCKER_IMAGE = "chaitanyapandeygspann/python-project"
        DOCKER_TAG = "1.0.${BUILD_NUMBER}"
        IMAGE_TAG = "${DOCKER_IMAGE}:${DOCKER_TAG}"
        GITOPS_REPO = "https://github.com/BackstageSSPPoC/k8s-manifests.git"
        APP_PORTS = "5000"
        DEPLOY_ENV = "dev"
        DEPLOY_NAMESPACE = "dev"
        PYTHONUNBUFFERED = "1"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Decide Pipeline Flow') {
            steps {
                script {
                    echo "Branch: ${env.BRANCH_NAME}"
                    echo "GIT_BRANCH: ${env.GIT_BRANCH}"

                    if (env.BRANCH_NAME == "main" || env.BRANCH_NAME.endsWith("/main") || env.GIT_BRANCH?.endsWith("main")) {
                        echo "Main branch detected → CI + CD"
                        env.RUN_MODE = "cd"
                    } else {
                        echo "Non-main branch → CI only"
                        env.RUN_MODE = "ci"
                    }
                }
            }
        }

// ================= CI STAGES =================

        stage('Setup Environment') {
            steps {
                sh '''
                python3 -m venv venv
. venv/bin/activate
pip3 install --upgrade pip
if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
if [ -f pyproject.toml ]; then pip3 install poetry && poetry install; fi
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                . venv/bin/activate && pip3 install -r requirements.txt || true
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate && python3 -m pytest --tb=short || true
                '''
            }
        }

        stage('SonarQube Analysis & Quality Gate') {
              steps {
                  script {
                      def scannerHome = tool 'sonar-scanner'
                      withSonarQubeEnv('SonarQube') {
                          sh """
                              . venv/bin/activate && ${scannerHome}/bin/sonar-scanner \
                                  -Dsonar.projectKey=${APP_NAME} \
                                  -Dsonar.python.version=3 -Dsonar.sources=.
                          """
                      }
                      timeout(time: 5, unit: 'MINUTES') {
                          waitForQualityGate abortPipeline: true
                      }
                  }
              }
          }

// ================= CD STAGES =================

        stage('Build Docker Image') {
            when {
                expression { env.RUN_MODE == "cd" }
            }
            steps {
                sh "docker build  -t ${IMAGE_TAG} ."
            }
        }

        stage('Login to Docker Registry') {
            when {
                expression { env.RUN_MODE == "cd" }
            }
            steps {
                script {
                    withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
                }
            }
        }

        stage('Push Docker Image') {
            when {
                expression { env.RUN_MODE == "cd" }
            }
            steps {
                sh 'docker push ${IMAGE_TAG}'
            }
        }

        stage('Update GitOps Repo') {
            when {
                expression { env.RUN_MODE == "cd" }
            }
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    rm -rf k8s-manifests

                    git clone --depth 1 https://${GITHUB_TOKEN}@github.com/BackstageSSPPoC/k8s-manifests.git
                    cd k8s-manifests

                    # ArgoCD Application yaml
                    mkdir -p argocd/
                    cp ../manifest-templates/application.yaml argocd/${APP_NAME}-${DEPLOY_ENV}.yaml || true

                    # Deployment / Service / Ingress — env specific folder
                    mkdir -p apps/${APP_NAME}/${DEPLOY_ENV}
                    cp ../manifest-templates/deployment.yaml apps/${APP_NAME}/${DEPLOY_ENV}/ || true
                    cp ../manifest-templates/service.yaml apps/${APP_NAME}/${DEPLOY_ENV}/ || true
                    cp ../manifest-templates/ingress.yaml apps/${APP_NAME}/${DEPLOY_ENV}/ || true

                    # Replace placeholders in manifest files
                    sed -i "s|\\${APP_NAME}|${APP_NAME}|g"         apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true
                    sed -i "s|\\${DOCKER_IMAGE}|${IMAGE_TAG}|g"    apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true
                    sed -i "s|\\${APP_PORT}|${APP_PORTS}|g"        apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true
                    sed -i "s|\\${NAMESPACE}|${DEPLOY_NAMESPACE}|g" apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true

                    sed -i "s|\\${APP_NAME}|${APP_NAME}|g"         argocd/${APP_NAME}-${DEPLOY_ENV}.yaml || true
                    sed -i "s|\\${NAMESPACE}|${DEPLOY_NAMESPACE}|g" argocd/${APP_NAME}-${DEPLOY_ENV}.yaml || true

                    git config user.email "jenkins@local"
                    git config user.name "jenkins"
                    git add .
                    git commit -m "[${DEPLOY_ENV}] Deploy ${APP_NAME} build ${BUILD_NUMBER}" || echo "No changes to commit"
                    git push origin main
                    '''
                }
            }
        }
    }

    post {
        always {
            sh "docker logout || true"
            sh "docker image prune -f || true"
        }
        success {
            echo "✅ Pipeline SUCCESS — ${APP_NAME}:${DOCKER_TAG} → ${DEPLOY_ENV}"
        }
        failure {
            echo "❌ Pipeline FAILED — check logs above"
        }
    }
}